version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '8080:8080'
    environment:
      - MARIADB_HOST =mariadb
      - MARIADB_PORT_NUMBER=3306
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - drupal_data:/bitnami
  
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_PASSWORD=30718092
      - MARIADB_USER =YAM428
      - MARIADB_DATABASE=final
    volumes:
      - mariadb_data:/bitnami
  
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.config"/etc/nginx/nginx.conf
      - drupal_data:/bitnami

  certbot:
    image: certbot
    volumes:
      - ./certbot.conf:/etc/letsencrypt/cli.ini
      - ./certbot-data:/etc/letsencrypt
      - drupal_data:/bitnami
  
volumes:
  drupal_data:
  mariadb_data:
